### ISSUE TITLE
Support for High Availbility

### ISSUE THREAD

**Issue by louisjsyoo** [weka/csi-wekafs#44]
Hello,
Recently I faced some issues while using `csi-wekafs` plugin, which `csi-wekafs-controller` POD stucked by some reason and then all `csi-wekafs-node` PODs can't communicate with `csi-wekafs-controller` POD.

And It seems that `csi-wekafs-controller` POD which was spawned from statefulset is not configured as supporting HA, only number of replicas is set to 1.

I'm wondering that If I change `replicas: 1` to `replicas: 3` or something else, then all behaviors like attaching, resizing, mounting, unpublishing, ... are working well?

Thanks.

**Comment by sergeyberezansky** [comment]
Hello Louis,
First of all, if you have encountered a controller pod freeze, please open an issue and provide the logs of `wekafs` container for the `csi-wekafs-controller-X` so we would be able to analyze it and resolve the issue. 
It is important to provide the whole log rather than last lines, since some important information is printed only in the beginning of plugin execution. Also, if you are aware of some specific issue that caused the pod to freeze, please specify it.

In general, CSI specifications require full idempotence for operations. Weka CSI plugin is by intention developed to be completely stateless, and preserves all the necessary data on Weka storage or inside Kubernetes manifests. 
Repeating requests for operations should be handled by all controllers independently (and it might happen practically in parallel).  Hence, having too much controllers could increase risk of some race conditions, but even in such case, if from some reason request fails, it will succeed on the next retry.
So you definitely can set number of replicas to 2 or 3. Please feel free to report any issues if you observe such. And don't forget the `wekafs` container logs of all controller replicas, of course.

**Comment by sergeyberezansky** [comment]
Hello Louis,
The plugin was updated with 2 controller replicas by default.

**Comment by jslouisyou** [comment]
Thanks @sergeyberezansky .
BTW, Is the next release version going to named as "2.0", not "1.0"?
And when will the next version be released?

**Comment by sergeyberezansky** [comment]
The version will be released together with Weka 4.2, pretty soon.
It will be indeed called 2.0.
Thank you

**Comment by jslouisyou** [comment]
Thanks.
Is it compatible with Weka 3.13.5.8?

**Comment by sergeyberezansky** [comment]
Hi, although some of the new functionality might work, it requires at least version 3.14, and for full feature support, version 4.2 is required.

Regardless, i would suggest you to coordinate upgrade with the customer success team

**Comment by sergeyberezansky** [comment]
Implemented in release 2.0.0
