### ISSUE TITLE
Unable to attach or mount volumes, timed out waiting for the condition

### ISSUE THREAD

**Issue by jslouisyou** [weka/csi-wekafs#66]
Hello,
I faced issue that PVC mount get timed out when one pod requests multiple PVC mount.
Pod trys to mount but any volume can't be mounted, these PVC mounts are retried several times and finally pod can't be startup.

Here's my condition.
I made two PV (hereby static provision I used), and these two PV are sharing same sub-directory path.

I ran an model and this model create its log in same path `dir/v1/storageclass-test/jslouisyou/model/` in this case, and below two PV are attached.

```
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: "1"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pv-output-model
    namespace: default
    resourceVersion: "27069727"
    uid: 3f985fdd-966b-452c-97c1-81d10cdc2e2b
  csi:
    driver: csi.weka.io
    volumeHandle: dir/v1/storageclass-test/jslouisyou/model/
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```
```
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: "1"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pv-output-log
    namespace: default
    resourceVersion: "27069647"
    uid: 1b558ff7-b2c3-4052-a013-8340d2ae1d47
  csi:
    driver: csi.weka.io
    volumeHandle: dir/v1/storageclass-test/jslouisyou/model/
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```

but when I tried to create a new pod, then `Unable to attach or mount volumes, timed out waiting for the condition` issue occurs and pod can't be started.

```
$ kubectl describe pod -n default test-0
...
Volumes:
  model:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pv-output-model
    ReadOnly:   false
  log:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pv-output-log
    ReadOnly:   false

...
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  67s (x156 over 5h52m)  kubelet  (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[log model], unattached volumes=[${REDACTED} log model]: timed out waiting for the condition
```

I found that PVC mount can be done when I try to mount just one PV mount, but multiple mount with same subpath is failed.

This issue also happens in `longhorn` (NFS filesystem), 
And people have similar issues with multiple mounts:
https://github.com/kubernetes/kubernetes/issues/110158
https://stackoverflow.com/questions/53383994/error-marking-master-timed-out-waiting-for-the-condition-kubernetes

and this issue also happens in EFS CSI driver:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/100#issuecomment-551293780

I think that many CSI drivers share this issue but EFS CSI driver resolved it by itself.

So I'm wondering that is this expected behavior?
If any user try to mount multiple volume, then these multiple volume should have different sub-directory path?

Thanks.

**Comment by sergeyberezansky** [comment]
According to CSI specifications, which can be spotted, for example, here
https://kubernetes.io/docs/concepts/storage/volumes/#csi
Or in developer documentation, a particular storage location must be identified uniquely by a single PersistentVolume object.

Hence, static provisioning of the same filesystem or directory path via multiple persistent volume objects is not allowed.

> volumeHandle: A string value that uniquely identifies the volume. This value must correspond to the value returned in the volume.id field of the CreateVolumeResponse by the CSI driver as defined in the CSI spec. The value is passed as volume_id on all calls to the CSI volume driver when referencing the volume.

Since volumeHandle (or volume ID) is used by CSI and Kubernetes for internally mounting the storage location, having same volumeHandle for same storage path will usually cause the second mount to fail (or even not start)

The correct way for provisioning the same data to multiple pods is by shared binding of the PersistentVolumeClaim, assuming that the storage vendor supports shared access to this type of volume and the correct access mode is indeed defined by the PVC.
Weka CSI Plugin supports ReadWriteOnce and ReadWriteMany
